### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [eybmv/franklin-w-dixon_the-missing-chums#1]
# Semantics

- [x] Let’s remove the `<em>`s from the song in chapter 1. Per [8.2.1](https://standardebooks.org/manual/1.7.4/8-typography#8.2.1) we don’t need to use both italics and quotes.

# CSS

- [x] We should add the [small-caps CSS](https://standardebooks.org/manual/1.7.4/7-high-level-structural-patterns#7.7.3.5.1) for letter recipients and salutations.

# Metadata

- [x] The Wikipedia link should be to `https://en.wikipedia.org/wiki/Franklin_W._Dixon` (the version you have is to a redirect page). Make sure to update the colophon too.
- [x] The IA link should be to `https://archive.org/details/the-missing-chums` (the trailing slash should be removed). This also needs to be updated in the colophon and imprint.
- [x] `portrayals of race and women` in the long description reads a little awkwardly to me, since “race” and “women” aren’t in the same category of nouns. “Ethnic minorities and women” or “race and gender” would make more sense to me.

**Comment by eybmv** [comment]
The salutation/recipient in the letter aren't in caps in the source. Is that fine? Is this one of the "The Manual Compels You" cases?

**Comment by weijia-cheng** [comment]
That's fine, you can add the styling regardless.
